name: Deploy extract Lambda

on:
  push:
    branches: [ "main" ]
    paths:
      - "lambda_extract/**"
      - ".github/workflows/deploy-extract-lambda.yml"

permissions:
  id-token: write
  contents: read

concurrency:
  group: deploy-db-lambda
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ECR_REPOSITORY: llama_extract_lambda
      LAMBDA_FUNCTION_NAME: llama_parse_extractor2


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_PROD }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image (linux/amd64)
        working-directory: lambda_extract
        uses: docker/build-push-action@v6
        with:
          context: ./lambda_extract
          file:  ./lambda_extract/Dockerfile.lambda-build
          platforms: linux/amd64
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Update Lambda to new image (use SHA tag)
        run: |
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}"
          aws lambda update-function-code \
            --function-name "${{ env.LAMBDA_FUNCTION_NAME }}" \
            --image-uri "$IMAGE_URI" \
            --publish \
            --output json
